v1.0 scss, css module, ts, images
CodersCamp2020-HK/CodersCamp2020.Project.TypeScript.Chess pull request #1
Opened 2021-01-20 14:49 UTC by bat098

2021-01-20 22:49 UTC, htk4 requested changes
Mógłbyś od razu dodać github workflow jako CI. Możesz zrobić copy-past z https://github.com/CodersCamp2020-HK/CodersCamp2020.Project.JavaScript.StarWarsQuiz/blob/main/.github/workflows/node.js.yml zachowując taką samą strukturę katalogów.
Powinno działać o ile w package.json będą komendy:  `build`, `test:cov`, `lint`.
Możesz od razu dodać "pusty test" (`expect(true).toBe(true)`) żeby sprawdzić czy CI działa poprawnie.

2021-01-20 22:49 UTC, htk4 commented on package.json
> +        "start": "tsc --watch",
Nie powinno być `webpack --watch` ?

2021-01-20 22:49 UTC, htk4 commented on package.json
> +        "test": "npx jest",
Wystarczy `jest`
Możesz jeszcze dodać:
```
"test:dev": "jest --watch",
"test:cov": "jest --coverage"
```

2021-01-20 22:49 UTC, htk4 commented on package.json
> +        "lint": "eslint '*/**/*.{js,ts,tsx}' --quiet --fix"
Chyba tak, będzie lepiej: `eslint --ignore-path .gitignore --fix .`

2021-01-20 22:49 UTC, htk4 commented on package.json
> +    "author": "Meo",
Na pewno? 😃

2021-01-20 22:49 UTC, htk4 commented on webpack.config.js
> +const path = require('path');
Wygląda dobrze 👍🏻

2021-01-20 22:49 UTC, htk4 commented on tsconfig.json
> +    "target": "es5", /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */
`es2020` ?

2021-01-20 22:57 UTC, bat098 commented on package.json
> +        "start": "tsc --watch",
--watch do builda? Za każdym razem gdy cos zmieniamy ma builda robić? Mało wydajne?

2021-01-21 11:55 UTC, htk4 commented on package.json
> +        "start": "tsc --watch",
Chodzi o live reloading, najlepiej użyć : https://webpack.js.org/guides/development/#using-webpack-dev-server, ale `webpack --watch` też wystarczy :wink:.

2021-01-21 11:57 UTC, htk4 commented on package.json
> +        "start": "tsc --watch",
Chodzi o `start`

2021-01-22 20:22 UTC, KrolMateusz approved these changes

2021-01-22 20:22 UTC, htk4 approved these changes

2021-01-22 20:23 UTC, merged