Chessboard component
CodersCamp2020-HK/CodersCamp2020.Project.TypeScript.Chess pull request #27
Opened 2021-01-26 16:53 UTC by Haivex

Chessboard with Axis is generated and has methods to change single tile

2021-02-04 21:24 UTC, KrolMateusz requested changes

2021-02-04 21:24 UTC, KrolMateusz commented on debug.log
> +[0203/201623.977:ERROR:file_io_win.cc(180)] CreateFile C:\Program Files (x86)\settings.dat: Odmowa dost�pu. (0x5)
To nie jest potrzebne 😅

2021-02-04 21:24 UTC, KrolMateusz commented on src/app/components/ChessBoard/ChessBoardComponent.ts
> +export class ChessBoardComponent {
Ta klasa może być wykorzystana jako presenter

2021-02-04 21:24 UTC, KrolMateusz commented on debug.log
> +[0203/201623.977:ERROR:file_io_win.cc(180)] CreateFile C:\Program Files (x86)\settings.dat: Odmowa dost�pu. (0x5)
Można usunąć

2021-02-04 21:24 UTC, KrolMateusz commented on src/app/components/ChessBoard/ChessBoardComponent.ts
> +        this.wrapper.appendChild(this._board);
Możesz wykorzystać taki zapis:
```ts
this.wrapper.appendChild(this.__verticalAxi, this.__horizontalAxi, this.__board)
```

2021-02-04 21:24 UTC, KrolMateusz commented on src/app/components/ChessBoard/ChessBoardComponent.ts
> +            }
Można ładnie zapisać korzystając z operatora trójargumentowego.
```ts
currentTile = row % 2 ? blackTile : whiteTile;
```

2021-02-04 21:24 UTC, KrolMateusz commented on src/app/components/ChessBoard/ChessBoardComponent.ts
> +    public wrapper: HTMLDivElement;
wrapper też może być prywatny z publicznym getterem

2021-02-04 22:59 UTC, Haivex commented on debug.log
> +[0203/201623.977:ERROR:file_io_win.cc(180)] CreateFile C:\Program Files (x86)\settings.dat: Odmowa dost�pu. (0x5)
Ups zapomniałem usunąć :D

2021-02-04 23:01 UTC, Haivex commented on src/app/components/ChessBoard/ChessBoardComponent.ts
> +export class ChessBoardComponent {
Mógłbyś proszę dokładniej wyjaśnić?

2021-02-05 12:52 UTC, KrolMateusz submitted a review, later dismissed

2021-02-06 18:12 UTC, dudeek approved these changes

2021-02-06 18:58 UTC, KrolMateusz approved these changes

2021-02-06 20:03 UTC, bat098 approved these changes

2021-02-06 20:03 UTC, KrolMateusz approved these changes

2021-02-06 20:03 UTC, Ania-Em approved these changes

2021-02-06 20:03 UTC, merged