Possibility knight moves #18
CodersCamp2020-HK/CodersCamp2020.Project.TypeScript.Chess pull request #33
Opened 2021-01-30 16:35 UTC by blackrabbit2

-All possible moves for knight

2021-02-02 13:33 UTC, KrolMateusz requested changes

2021-02-02 13:33 UTC, KrolMateusz commented on src/app/utils/PossibleKnightMoves.ts
> +        const actualKnightPositionY = knight.cord.y + combination[1];
Do pozycji skoczka można odwołać się za pomocą parametru `cord`, a nie obiektu `knight` (nie będziesz miała o nim informacji).
```ts
const actualKnightPositionX = cord.x + combination[0];
const actualKnightPositionY = cord.y + combination[1];
```

2021-02-02 13:33 UTC, KrolMateusz commented on src/app/utils/PossibleKnightMoves.ts
> +}
Funkcja powinna zwracać `possibleMoves`

2021-02-02 13:33 UTC, KrolMateusz commented on src/app/utils/PossibleKnightMoves.ts
> +function getPossibleMovesForKnight(cord: Cord, boardState: IChessBoard) {
Parametr `boardState: IChessBoard` nie jest potrzebny dla funkcji, która zwraca wszystkie możliwe ruchy dla skoczka, ponieważ nie sprawdzamy ruchów w tym miejscu

2021-02-02 13:33 UTC, KrolMateusz commented on src/app/utils/PossibleKnightMoves.ts
> +    for (const combination in possibleCombinations) {
Pętla powinna być `for of` zamiast `for in` ,bo chcemy iterować po wartość ([1, 2]), a nie po kluczach. Te klucze są stringami i niepoprawne koordynaty są wrzucane do tablicy.

2021-02-02 13:33 UTC, KrolMateusz commented on src/app/utils/PossibleKnightMoves.ts
> +        possibleMoves.push({ x: actualKnightPositionX, y: actualKnightPositionY });
Można wrzucić wyżej i wykonać wszystko w jednej pętli np:
```ts
possibleMoves.push({ x: cord.x + combination[1], y: cord.y + combination[0] });
```

2021-02-03 20:24 UTC, KrolMateusz approved these changes

2021-02-06 18:11 UTC, dudeek approved these changes

2021-02-06 18:38 UTC, merged