Chessboard class
CodersCamp2020-HK/CodersCamp2020.Project.TypeScript.Chess pull request #38
Opened 2021-02-01 17:31 UTC by KrolMateusz

2021-02-02 16:09 UTC, Haivex requested changes
Widzę że Github Actions czepia się typu any, typ unknown by nie zadziałał?

2021-02-02 17:58 UTC, Haivex commented on src/app/utils/ChessboardHelpers.ts
> +    result[1] = blackPawns;
:+1: podmiana całego rzędu :)

2021-02-06 18:10 UTC, dudeek approved these changes

2021-02-06 18:53 UTC, Haivex submitted a review, later dismissed

2021-02-06 22:54 UTC, bat098 approved these changes

2021-02-07 09:43 UTC, dudeek approved these changes

2021-02-07 16:36 UTC, Haivex approved these changes

2021-02-07 16:37 UTC, merged