Captured table
CodersCamp2020-HK/CodersCamp2020.Project.TypeScript.Chess pull request #39
Opened 2021-02-02 15:58 UTC by Ania-Em

2021-02-02 20:05 UTC, dudeek submitted a review, later dismissed

2021-02-02 20:30 UTC, KrolMateusz submitted a review, later dismissed

2021-02-04 21:15 UTC, KrolMateusz requested changes

2021-02-04 21:15 UTC, KrolMateusz commented on src/app/components/game/capturedTable/CapturedTable.ts
> +        this.__element.classList.add(styles[side]);
Możesz zapisać kilka klas po przecinku, czyli `this.__element.classList.add(styles.capturedWrapper, styles[side]);`

2021-02-04 22:57 UTC, KrolMateusz approved these changes

2021-02-06 18:21 UTC, bat098 submitted a review, later dismissed

2021-02-06 18:27 UTC, bat098 approved these changes

2021-02-06 18:32 UTC, bat098 submitted a review, later dismissed

2021-02-06 18:34 UTC, KrolMateusz approved these changes

2021-02-06 18:34 UTC, bat098 approved these changes

2021-02-06 18:34 UTC, dudeek approved these changes

2021-02-06 18:35 UTC, merged