Footer
CodersCamp2020-HK/CodersCamp2020.Project.TypeScript.Chess pull request #61
Opened 2021-02-04 12:32 UTC by Ania-Em

-Podmienione obrazki svg
-Dodany napis Coderscamp

2021-02-04 12:56 UTC, Haivex submitted a review, later dismissed

2021-02-04 21:10 UTC, KrolMateusz requested changes

2021-02-04 21:10 UTC, KrolMateusz commented on src/app/components/footer/Footer.ts
> +        codersCampText.appendChild(campText);
Można to zapisać w jednej linii, przy pomocy `innerHTML`, zamiast tworzyć nowego spana.
```ts
codersCampText.innerHTML = '.Coders<span>Camp</span>'
```

2021-02-04 21:10 UTC, KrolMateusz commented on src/app/components/footer/Footer.ts
> +        this.__element.appendChild(footerImageRight);
Zamiast kilku instrukcji `appendChild` możesz napisać
```ts
this.__element.appendChild(footerImageLeft, footerTextWrapper, footerImageRight)
```

2021-02-04 21:48 UTC, Haivex commented on src/app/components/footer/Footer.ts
> +        this.__element.appendChild(footerImageRight);
Dobrze wiedzieć :)

2021-02-04 22:46 UTC, Ania-Em commented on src/app/components/footer/Footer.ts
> +        this.__element.appendChild(footerImageRight);
Trzeba zrobić append, bo appendChild tylko jeden argument przyjmuje, ale właśnie warto zapamiętać ;)

2021-02-04 22:56 UTC, KrolMateusz approved these changes

2021-02-06 18:23 UTC, bat098 approved these changes

2021-02-06 18:24 UTC, merged